// This file will be auto-generated by `diesel print-schema` after the first
// migration run. It is checked in as an empty placeholder so the crate compiles
// before a database is available.
//
// Run `diesel print-schema > src/infrastructure/db/schema.rs` after applying
// migrations to regenerate.

diesel::table! {
    users (id) {
        id -> Uuid,
        username -> Varchar,
        email -> Varchar,
        password_hash -> Varchar,
        display_name -> Varchar,
        account_status -> Varchar,
        failed_login_count -> Int4,
        locked_until -> Nullable<Timestamptz>,
        last_login_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    sessions (id) {
        id -> Uuid,
        user_id -> Uuid,
        token_hash -> Varchar,
        device_fingerprint -> Nullable<Varchar>,
        ip_address -> Nullable<Varchar>,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
        last_activity_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    roles (id) {
        id -> Uuid,
        name -> Varchar,
        description -> Nullable<Text>,
        is_system_role -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    permissions (id) {
        id -> Uuid,
        resource -> Varchar,
        action -> Varchar,
        description -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    role_permissions (role_id, permission_id) {
        role_id -> Uuid,
        permission_id -> Uuid,
    }
}

diesel::table! {
    user_roles (user_id, role_id) {
        user_id -> Uuid,
        role_id -> Uuid,
        scope_type -> Nullable<Varchar>,
        scope_id -> Nullable<Uuid>,
        granted_at -> Timestamptz,
        granted_by -> Nullable<Uuid>,
    }
}

diesel::table! {
    candidates (id) {
        id -> Uuid,
        first_name -> Varchar,
        last_name -> Varchar,
        email -> Varchar,
        phone_encrypted -> Nullable<Bytea>,
        ssn_last4_encrypted -> Nullable<Bytea>,
        resume_storage_key -> Nullable<Varchar>,
        source -> Nullable<Varchar>,
        tags -> Array<Text>,
        notes -> Nullable<Text>,
        organization_id -> Nullable<Uuid>,
        created_by -> Nullable<Uuid>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        latitude -> Nullable<Float8>,
        longitude -> Nullable<Float8>,
    }
}

diesel::table! {
    offers (id) {
        id -> Uuid,
        candidate_id -> Uuid,
        title -> Varchar,
        department -> Nullable<Varchar>,
        compensation_encrypted -> Nullable<Bytea>,
        start_date -> Nullable<Date>,
        status -> Varchar,
        expires_at -> Nullable<Timestamptz>,
        template_id -> Nullable<Uuid>,
        clause_version -> Nullable<Varchar>,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        salary_cents -> Nullable<Int8>,
        bonus_target_pct -> Nullable<Float8>,
        equity_units -> Nullable<Int4>,
        pto_days -> Nullable<Int2>,
        k401_match_pct -> Nullable<Float8>,
        currency -> Varchar,
    }
}

diesel::table! {
    approval_steps (id) {
        id -> Uuid,
        offer_id -> Uuid,
        step_order -> Int4,
        approver_id -> Uuid,
        decision -> Varchar,
        decided_at -> Nullable<Timestamptz>,
        comments -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    onboarding_checklists (id) {
        id -> Uuid,
        offer_id -> Uuid,
        candidate_id -> Uuid,
        assigned_to -> Nullable<Uuid>,
        due_date -> Nullable<Date>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    onboarding_items (id) {
        id -> Uuid,
        checklist_id -> Uuid,
        title -> Varchar,
        description -> Nullable<Text>,
        item_order -> Int4,
        status -> Varchar,
        requires_upload -> Bool,
        upload_storage_key -> Nullable<Varchar>,
        health_attestation_encrypted -> Nullable<Bytea>,
        required -> Bool,
        item_due_date -> Nullable<Date>,
        completed_at -> Nullable<Timestamptz>,
        completed_by -> Nullable<Uuid>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    office_sites (id) {
        id -> Uuid,
        code -> Varchar,
        name -> Varchar,
        address -> Nullable<Text>,
        latitude -> Nullable<Float8>,
        longitude -> Nullable<Float8>,
        timezone -> Varchar,
        is_active -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    booking_slots (id) {
        id -> Uuid,
        site_id -> Uuid,
        slot_date -> Date,
        start_time -> Time,
        end_time -> Time,
        capacity -> Int4,
        booked_count -> Int4,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    booking_orders (id) {
        id -> Uuid,
        candidate_id -> Uuid,
        site_id -> Uuid,
        status -> Varchar,
        scheduled_date -> Date,
        scheduled_time_start -> Nullable<Time>,
        scheduled_time_end -> Nullable<Time>,
        notes -> Nullable<Text>,
        slot_id -> Nullable<Uuid>,
        hold_expires_at -> Nullable<Timestamptz>,
        agreement_signed_by -> Nullable<Varchar>,
        agreement_signed_at -> Nullable<Timestamptz>,
        agreement_hash -> Nullable<Varchar>,
        breach_reason -> Nullable<Text>,
        breach_reason_code -> Nullable<Varchar>,
        exception_detail -> Nullable<Text>,
        idempotency_key -> Nullable<Varchar>,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    booking_restrictions (id) {
        id -> Uuid,
        candidate_id -> Uuid,
        restriction_type -> Varchar,
        reason -> Nullable<Text>,
        is_active -> Bool,
        expires_at -> Nullable<Timestamptz>,
        created_by -> Nullable<Uuid>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    controlled_vocabularies (id) {
        id -> Uuid,
        category -> Varchar,
        value -> Varchar,
        label -> Varchar,
        sort_order -> Int4,
        is_active -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    historical_queries (id) {
        id -> Uuid,
        user_id -> Uuid,
        query_text -> Text,
        filters -> Jsonb,
        result_count -> Nullable<Int4>,
        executed_at -> Timestamptz,
    }
}

diesel::table! {
    reporting_subscriptions (id) {
        id -> Uuid,
        user_id -> Uuid,
        report_type -> Varchar,
        parameters -> Jsonb,
        cron_expression -> Nullable<Varchar>,
        is_active -> Bool,
        last_run_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    dashboard_versions (id) {
        id -> Uuid,
        dashboard_key -> Varchar,
        version -> Int4,
        layout -> Jsonb,
        published_by -> Uuid,
        published_at -> Timestamptz,
    }
}

diesel::table! {
    reporting_alerts (id) {
        id -> Uuid,
        subscription_id -> Uuid,
        severity -> Varchar,
        message -> Text,
        acknowledged -> Bool,
        acknowledged_by -> Nullable<Uuid>,
        acknowledged_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        delivery_meta -> Nullable<Jsonb>,
    }
}

diesel::table! {
    integration_connectors (id) {
        id -> Uuid,
        name -> Varchar,
        connector_type -> Varchar,
        base_url -> Nullable<Varchar>,
        auth_config_encrypted -> Nullable<Bytea>,
        is_enabled -> Bool,
        created_by -> Uuid,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    integration_sync_state (id) {
        id -> Uuid,
        connector_id -> Uuid,
        entity_type -> Varchar,
        last_sync_at -> Nullable<Timestamptz>,
        last_sync_cursor -> Nullable<Varchar>,
        status -> Varchar,
        error_message -> Nullable<Text>,
        record_count -> Int4,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    idempotency_keys (key) {
        key -> Varchar,
        user_id -> Uuid,
        request_path -> Varchar,
        request_hash -> Varchar,
        response_status -> Int4,
        response_body -> Nullable<Jsonb>,
        created_at -> Timestamptz,
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    audit_events (id) {
        id -> Uuid,
        actor_id -> Nullable<Uuid>,
        actor_ip -> Nullable<Varchar>,
        action -> Varchar,
        resource_type -> Varchar,
        resource_id -> Nullable<Uuid>,
        old_value -> Nullable<Jsonb>,
        new_value -> Nullable<Jsonb>,
        metadata -> Jsonb,
        correlation_id -> Nullable<Uuid>,
        created_at -> Timestamptz,
    }
}

// Foreign key associations
diesel::joinable!(sessions -> users (user_id));
diesel::joinable!(role_permissions -> roles (role_id));
diesel::joinable!(role_permissions -> permissions (permission_id));
diesel::joinable!(offers -> candidates (candidate_id));
diesel::joinable!(approval_steps -> offers (offer_id));
diesel::joinable!(onboarding_checklists -> offers (offer_id));
diesel::joinable!(onboarding_items -> onboarding_checklists (checklist_id));
diesel::joinable!(booking_slots -> office_sites (site_id));
diesel::joinable!(booking_orders -> office_sites (site_id));
diesel::joinable!(booking_orders -> booking_slots (slot_id));
diesel::joinable!(historical_queries -> users (user_id));
diesel::joinable!(reporting_alerts -> reporting_subscriptions (subscription_id));
diesel::joinable!(integration_sync_state -> integration_connectors (connector_id));

diesel::allow_tables_to_appear_in_same_query!(
    users,
    sessions,
    roles,
    permissions,
    role_permissions,
    user_roles,
    candidates,
    offers,
    approval_steps,
    onboarding_checklists,
    onboarding_items,
    office_sites,
    booking_slots,
    booking_orders,
    booking_restrictions,
    controlled_vocabularies,
    historical_queries,
    reporting_subscriptions,
    dashboard_versions,
    reporting_alerts,
    integration_connectors,
    integration_sync_state,
    idempotency_keys,
    audit_events,
);
